# Generated by Django 4.1.1 on 2022-09-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_article_image_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
